### ISSUE TITLE
The validation details should be mentioned in the form itself for the user

### ISSUE THREAD

**Issue by JayashreeSelvarangam** [fssa-batch3/praveenkumar.sekar__web_project#11]
### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/profile/profile
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1011 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--home-bakery-pks.netlify.app%2Fpages%2Fprofile%2Fprofile&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1011x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--home-bakery-pks.netlify.app/pages/profile/profile)

**Comment by PKS-formido** [comment]
close pannu yaa
