### ISSUE TITLE
After deleting the profile out the header is not get changed to the header which is supposed to be in before login. 

### ISSUE THREAD

**Issue by JayashreeSelvarangam** [fssa-batch3/praveenkumar.sekar__web_project#12]
### Steps to reproduce
1. 
2. 
3. 

```
Path:      /index.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1011 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--home-bakery-pks.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1011x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--home-bakery-pks.netlify.app/index.html)

**Comment by PKS-formido** [comment]
I have fixed the issue.
