### ISSUE TITLE
Quantity of Product in cart.

### ISSUE THREAD

**Issue by PKS-formido** [fssa-batch3/praveenkumar.sekar__web_project#4]
### Description of issue
When the price of the products in the cart other than the first one is increased or decreased the price of the first product in the cart increases or decreases. Whereas the quantity of the desired product isn't changed.

### Expected result
Quantities should change the price for all the products in the cart.

### Actual result
Price of the products on the cart doesn't change when quantity is modified excepte the first product.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /index.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 931 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--home-bakery-pks.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x931&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--home-bakery-pks.netlify.app/index.html)

**Comment by PKS-formido** [comment]
I have fixed the issue.

**Comment by JayashreeSelvarangam** [comment]
ok
