### ISSUE TITLE
There is a problem in adding prices in the products which were added to the add to cart.

### ISSUE THREAD

**Issue by JayashreeSelvarangam** [fssa-batch3/praveenkumar.sekar__web_project#6]
### Description of issue
When the product of the same kind with different prices add to the cart , the product's quantity is not increasing .

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/cart/cart
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1172 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--home-bakery-pks.netlify.app%2Fpages%2Fcart%2Fcart&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1172x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--home-bakery-pks.netlify.app/pages/cart/cart)

**Comment by PKS-formido** [comment]
I have fixed the issue.
